# Generated by Django 5.2.5 on 2025-09-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='diagram_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
