# Generated by Django 5.2.5 on 2025-09-11 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0003_alter_diagram_options_diagram_likes_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagram',
            options={},
        ),
        migrations.RemoveField(
            model_name='diagram',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='diagram',
            name='views_count',
        ),
        migrations.RemoveField(
            model_name='diagram',
            name='visibility',
        ),
        migrations.AlterField(
            model_name='diagram',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
