# Generated by Django 5.2.5 on 2025-09-11 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0004_alter_diagram_options_remove_diagram_likes_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagram',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='diagram',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diagram',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_diagrams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagram',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diagram',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('unlisted', 'Unlisted (Anyone with link)')], default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to=settings.AUTH_USER_MODEL),
        ),
    ]
